# Generated by Django 6.0.6 on 2026-06-21 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Příjem'), ('EXPENSE', 'Výdaj')], max_length=7)),
                ('category', models.CharField(choices=[('FOOD', 'Jídlo'), ('RENT', 'Bydlení/Nájem'), ('TRANSPORT', 'Doprava'), ('ENTERTAINMENT', 'Zábava'), ('OTHER', 'Ostatní')], default='OTHER', max_length=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('CZK', 'Kč (CZK)'), ('USD', '$ (USD)'), ('EUR', '€ (EUR)')], default='CZK', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
