# Generated by Django 6.0.6 on 2026-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Plat'), ('DIVIDEND', 'Dividendy'), ('BONUS', 'Bonus'), ('OTHER_INC', 'Ostatní Příjem'), ('FOOD', 'Jídlo'), ('RENT', 'Bydlení'), ('TRANSPORT', 'Doprava'), ('FUN', 'Zábava'), ('OTHER_EXP', 'Ostatní Výdaj')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Příjem'), ('EXPENSE', 'Výdaj')], max_length=10),
        ),
    ]
