# Generated by Django 6.0.6 on 2026-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('CZK', 'Kč (CZK)'), ('USD', '$ (USD)'), ('EUR', '€ (EUR)')], default='CZK', max_length=3),
        ),
    ]
